### ISSUE TITLE
Validate meta information

### ISSUE THREAD

**Issue by 5ouma** [5ouma/mobicard#134]
### ✏️ Describe the feature

It should be validated with [Zod](https://zod.dev) or [Valibot](https://valibot.dev) to make errors on the build.

### ✔︎ Confirm these checks

- [X] I searched the GitHub [Issues](https://github.com/5ouma/mobicard/issues) or [Discussions](https://github.com/5ouma/mobicard/discussions).
- [X] I tried with the latest version.
- [X] I agree to follow the [Code of Conduct](https://github.com/5ouma/mobicard/blob/main/.github/CODE_OF_CONDUCT.md).
